### ISSUE TITLE
Font-Size in app is different from configured `text-base`

### ISSUE THREAD

**Issue by MrSnoozles** [NativeScript/tailwind#182]
Hi @rigor789, and thank you for this incredible plugin. Is it possible to synchronize the app's font size with `tailwind.config.js` for all elements? Right now when I add the class `text-base` to a `Label`, that label gets much bigger.

One solution could be to just add whatever you need to your app.scss:

~~~
// app.scss
@layer base {
    Label,Textfield,TextView {
        @apply text-base;
    }
}
~~~

Maybe there's a more elegant solution though?

**Comment by rigor789** [comment]
`text-base` is 16px (1rem, but converted to dp/unitless) and every other size is scaled the same way 

```css
text-xs: font-size: 0.75rem; /* 0.75 * 16 = 12 */
/* etc. */
```

There's no way to change the base from 16 currently, perhaps it could be a config option?

**Comment by MrSnoozles** [comment]
The default font size for Android devices seems to be around 14.
I thought it might be useful to change that globally for all the elements. Right now, a Label with the class `text-sm` would look like a Label without a class. 

I thought it might be more intuitive for developers if we either:
1. Change the example tailwind.config.js in this repos Readme so the base size is 14 pixels too or
2. Somehow increase the default font size for all elements to 16 so it matches Tailwind`s default config

**Comment by MrSnoozles** [comment]
Going to close this because it's not really an issue. Still, it would be very intuitive if we could change the size of all text-elements simple by changing tailwinds "text-base" configuration. 
Adding some SCSS rules that users can copy into their app.scss to this package's readme would probably be the easiest solution. If you like the idea let me know.

**Comment by rigor789** [comment]
The way tailwind works on web is that it takes your base font size from the "scope" so if you set `html { font-size: 10px }` then everything will scale according to that (since it uses rems).

That's not quite simple to do in {N} - we could provide an option to change it - but it won't apply to all elements by default (tailwind doesn't touch that) so you'd still need to apply the `font-base` to elements.

Ideally we would implement support for `rem` units and then use tailwind font sizes as-is, and let the core internals calculate the dp/px size under the hood...
